version: '3.8'

services:
  # Serviço da nossa API Python/Flask
  web:
    build: .
    command: python app/main.py
    volumes:
      - .:/app
    ports:
      - "5001:5000" # Mapeia a porta 5000 do container para a 5001 da sua máquina
    env_file:
      - .env # Carrega as variáveis de ambiente do arquivo .env
    depends_on:
      - db

  # Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # Mapeia a porta 3306 do container para a 3306 da sua máquina

volumes:
  mysql_data:
